//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shinigamiZer0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbKutuphaneEntities : DbContext
    {
        public dbKutuphaneEntities()
            : base("name=dbKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblKitaplar> TblKitaplar { get; set; }
        public virtual DbSet<TblTurler> TblTurler { get; set; }
        public virtual DbSet<TblYazarlar> TblYazarlar { get; set; }
    }
}
